name: Robo_Vagas_Inatel

on:
  schedule:
    - cron: '0 12 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # ESSA LINHA ABAIXO Ã‰ A CHAVE MESTRA:
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Instalando bibliotecas
        run: pip install requests beautifulsoup4

      - name: Rodando o script
        env:
          MEU_TOKEN: ${{ secrets.TOKEN_BOT }}
          MEU_CHAT_ID: ${{ secrets.MEU_CHAT_ID }} 
        run: python vagas_inatel_automatizada.py

      - name: Guardando o caderninho (Salvar CSV no GitHub)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add vagas_estagio_inatel.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸ¤– Bot: Atualizando vagas antigas" && git push)
