name: Robo_Vagas_Inatel

on:
  schedule:
    - cron: '0 12 * * *' # Todo dia às 9h da manhã (Brasília)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Instalando bibliotecas
        run: pip install requests beautifulsoup4

      - name: Rodando o script
        env:
          # NOME_NO_PYTHON: ${{ secrets.NOME_NO_GITHUB }}
          MEU_TOKEN: ${{ secrets.TOKEN_BOT }}
          MEU_CHAT_ID: ${{ secrets.MEU_CHAT_ID }} 
        run: python vagas_inatel_automatizada.py
